name: Release a new version of tmdbcli.
run-name: ${{ github.actor }} is Releasing a new version 🚀
on: [push]
  # release:
  #   types: [published]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.6'
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: Just test
        run: |
          ls ${{ github.workspace }}
