name: Testing the tmdbcli.
run-name: ${{ github.actor }} is testing a new version of tmdbcli 🚀
on: [push]
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.6'
      - name: Go Unit tests
        run: |
          go test ./... -count=1
    #   - name: SonarQube
    #     run: |
    #       go test ./... -count=1
